# 1) Numpy

In [1]:
import numpy as np

#### 1-1) ndarry 생성

In [4]:
arr = np.array([1,2,3,4,5])
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(mat)

[1 2 3 4 5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(arr.ndim)
print(mat.ndim)

1
2


In [8]:
print(arr.shape)
print(mat.shape)

(5,)
(3, 4)


In [10]:
arr[3]

4

In [14]:
mat[2,1]

10

In [16]:
mat[1,[0,3]]

array([5, 8])

In [18]:
mat[0:2,1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [27]:
mat[1,:]

array([5, 6, 7, 8])

In [26]:
mat[1:2,:]

array([[5, 6, 7, 8]])

In [30]:
mat[:,-1]

array([ 4,  8, 12])

In [31]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
np.delete(mat, 2, axis = 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [35]:
mat2 = np.array([[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]])
print(mat2)
print(mat)

[[ -1  -2  -3  -4]
 [ -5  -6  -7  -8]
 [ -9 -10 -11 -12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
np.concatenate((mat,mat2))

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ -1,  -2,  -3,  -4],
       [ -5,  -6,  -7,  -8],
       [ -9, -10, -11, -12]])

In [37]:
np.concatenate((mat,mat2),axis=1)

array([[  1,   2,   3,   4,  -1,  -2,  -3,  -4],
       [  5,   6,   7,   8,  -5,  -6,  -7,  -8],
       [  9,  10,  11,  12,  -9, -10, -11, -12]])

In [38]:
import pandas as pd

In [40]:
data = pd.read_csv('Data.csv')
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [41]:
data2 = pd.read_csv('Data.csv', index_col = 'Country')
data2

Age   Salary Purchased
Country                         
France   44.0  72000.0        No
Spain    27.0  48000.0       Yes
Germany  30.0  54000.0        No
Spain    38.0  61000.0        No
Germany  40.0      NaN       Yes
France   35.0  58000.0       Yes
Spain     NaN  52000.0        No
France   48.0  79000.0       Yes
Germany  50.0  83000.0        No
France   37.0  67000.0       Yes

In [42]:
print(data.columns)

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')


In [46]:
np.genfromtxt('Data.csv',delimiter = ',', dtype = np.str_)

array([['Country', 'Age', 'Salary', 'Purchased'],
       ['France', '44', '72000', 'No'],
       ['Spain', '27', '48000', 'Yes'],
       ['Germany', '30', '54000', 'No'],
       ['Spain', '38', '61000', 'No'],
       ['Germany', '40', '', 'Yes'],
       ['France', '35', '58000', 'Yes'],
       ['Spain', '', '52000', 'No'],
       ['France', '48', '79000', 'Yes'],
       ['Germany', '50', '83000', 'No'],
       ['France', '37', '67000', 'Yes']], dtype='<U9')

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes
